### PR TITLE
fix: panic when read data out of range by disk cache

### LINKED ISSUE #1194: compaction panic when read disk cache
### Describe this problem

```bash
2023-09-05 11:59:38.852 ERRO [components/panic_ext/src/lib.rs:54] thread 'ceres-compact' panicked 'range end index 78088 out of range for slice of length 33814' at "components/object_store/src/disk_cache.rs:689"
   0: panic_ext::set_panic_hook::{{closure}}
             at /home/db/ceresdb/components/panic_ext/src/lib.rs:53:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/std/src/panicking.rs:692:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/std/src/panicking.rs:579:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/std/src/sys_common/backtrace.rs:137:18
   4: rust_begin_unwind
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/std/src/panicking.rs:575:5
   5: core::panicking::panic_fmt
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/panicking.rs:64:14
   6: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/slice/index.rs:77:5
   7: core::slice::index::slice_end_index_len_fail
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/slice/index.rs:69:9
   8: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/slice/index.rs:409:13
      core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/slice/index.rs:18:9
      <object_store::disk_cache::DiskCacheStore as object_store::ObjectStore>::get_range::{{closure}}
             at /home/db/ceresdb/components/object_store/src/disk_cache.rs:689:18
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/future/future.rs:125:9
      object_store::mem_cache::MemCacheStore::get_range_with_ro_cache::{{closure}}
             at /home/db/ceresdb/components/object_store/src/mem_cache.rs:196:57
      <object_store::mem_cache::MemCacheStore as object_store::ObjectStore>::get_range::{{closure}}
             at /home/db/ceresdb/components/object_store/src/mem_cache.rs:244:58
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/future/future.rs:125:9
      <analytic_engine::sst::parquet::async_reader::ChunkReaderAdapter as parquet_ext::meta_data::ChunkReader>::get_bytes::{{closure}}
             at /home/db/ceresdb/analytic_engine/src/sst/parquet/async_reader.rs:454:47
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/11d96b59307b1702fffe871bfc2d0145d070881e/library/core/src/future/future.rs:125:9
      parquet_ext::meta_data::fetch_parquet_metadata::{{closure}}
             at /home/db/ceresdb/components/parquet_ext/src/meta_data.rs:51:9
      analytic_engine::sst::parquet::async_reader::Reader::load_meta_data_from_storage::{{closure}}
             at /home/db/ceresdb/analytic_engine/src/sst/parquet/async_reader.rs:373:17

```

### Server version

$ ceresdb-server --version
CeresDB Server 
Version: 1.2.6-alpha
Git commit: 7f8faff79
Git branch: main
Opt level: 3
Rustc version: 1.69.0-nightly
Target: x86_64-unknown-linux-gnu
Build date: 2023-08-17T09:04:30.077953531Z

### Steps to reproduce

N/A

### Expected behavior

No panic

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ShiKaiWi**
## Rationale
Close #1194 

## Detailed Changes
Throw `OutOfRange` error when the query range is out of the file size.

## Test Plan
Add a new dedicated unit test for this case.

### CODE REVIEW

File: components/object_store/src/disk_cache.rs [hunk 1]
```diff
@@ -933,6 +949,42 @@ mod test {
...
+        }
+        let written_data = buf.freeze();
+        store
+            .inner
+            .put(&location, written_data.clone())
+            .await
+            .unwrap();
+
+        // Read one page out of range.
+        let start = written_data.len() / page_size * page_size + page_size / 2;
```
Comment (jiacai2050) [inline components/object_store/src/disk_cache.rs:972]: SInce page_size is explicit, I suggest use number literals,

File: components/object_store/src/disk_cache.rs [hunk 2]
```diff
@@ -933,6 +949,42 @@ mod test {
...
+        let range = start..start + page_size / 2;
+        let res = store.inner.get_range(&location, range).await;
+        assert!(res.is_err());
+
+        // Read multiple pages out of range.
+        let res = store
+            .inner
+            .get_range(
+                &location,
+                (written_data.len() / 2)..(written_data.len() * 2),
```
Comment (jiacai2050) [inline components/object_store/src/disk_cache.rs:982]: same with before.

**Review by jiacai2050 — APPROVED** [review]
LGTM
