### PR TITLE
fix: adopt new parquet api

### LINKED ISSUE #271: When upgrade to parquet 23, some usages are deprecated.
### Describe This Problem

When upgrade to parquet 23, some usages are deprecated. 
```
warning: use of deprecated struct `arrow_deps::parquet::arrow::ParquetFileArrowReader`: Use ParquetRecordBatchReaderBuilder instead
```

### Proposal

Remove `#[allow(deprecated)]` in `analytic_engine/src/sst/parquet/mod.rs` and `components/parquet/src/lib.rs`.
Use `ParquetRecordBatchReaderBuilder` to refactor `parquet reader`.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #271

# Rationale for this change
 
After #269, some parquet API is deprecated, this PR adopt to the new API.

# What changes are included in this PR?

Replace ParquetFileArrowReader with ParquetRecordBatchReader

# Are there any user-facing changes?

No
# How does this change test

Existing UT

### CODE REVIEW

File: analytic_engine/src/sst/parquet/encoding.rs [hunk 1]
```diff
@@ -946,9 +943,10 @@ mod tests {
 
         // read encoded records back, and then compare with input records
         let encoded_bytes = encoder.close().unwrap();
-        let reader = SerializedFileReader::new(Bytes::from(encoded_bytes)).unwrap();
-        let mut reader = ParquetFileArrowReader::new(Arc::new(reader));
-        let mut reader = reader.get_record_reader(2048).unwrap();
+        let mut reader = ParquetRecordBatchReaderBuilder::try_new(Bytes::from(encoded_bytes))
+            .unwrap()
```
Comment (ShiKaiWi) [inline analytic_engine/src/sst/parquet/encoding.rs:947]: Shall we return the error instead of panic here?

**Review by ShiKaiWi — APPROVED** [review]
LGTM
