### PR TITLE
fix: table name with quote

### LINKED ISSUE #113: table name with back quote has strange behavior in SDK
**Describe this problem**

run log:
```
DROP TABLE IF EXISTS `t0`;

affected_rows: 0

CREATE TABLE `t0`(a int, t timestamp NOT NULL, TIMESTAMP KEY(t)) ENGINE = Analytic;

affected_rows: 0

INSERT INTO TABLE `t0`(a, t) values(1,1);

affected_rows: 1

SELECT * FROM `t0`;

Failed to execute query, err: Server(ServerError { code: 500, msg: "Failed to create plan, query: SELECT * FROM `t0`;. Caused by: Failed to create plan, err:DataFusion Failed to plan, err:Execution error: MetaProvider not found" })
```

**Steps to reproduce**

add the following to a integration test
```sql
DROP TABLE IF EXISTS `t0`;

CREATE TABLE `t0`(a int, t timestamp NOT NULL, TIMESTAMP KEY(t)) ENGINE = Analytic;

INSERT INTO TABLE `t0`(a, t) values(1,1);

SELECT * FROM `t0`;
```

and run it

**Expected behavior**

the last SQL
```sql
SELECT * FROM `t0`;
```

should return data instead of reporting an error.

**Additional Information**

the client version is 
```
https://github.com/CeresDB/ceresdb-client-rs.git?rev=a935a0ebacd1304d69d25e3e8611afa7d64611d6
```

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #113 

# Rationale for this change
 

Table Name (or other identifiers) with back quotes should be treated as literal token. But our interpreter will use the token with back quotes which will lead to some inconsistent behaviors like reported in #113 

# What changes are included in this PR?

Replace `ObjectName` with `TableName` in parsed SQL statement to override the `ToString` implement, which will remove quotes and join every token with `.`

# Are there any user-facing changes?

No

# How does this change test

Unit test

### CODE REVIEW

File: sql/src/ast.rs [hunk 1]
```diff
@@ -26,6 +26,32 @@ pub enum Statement {
     Exists(ExistsTable),
 }
 
+#[derive(Debug, PartialEq)]
+pub struct TableName(ObjectName);
+
+impl TableName {
+    pub fn is_empty(&self) -> bool {
+        self.0 .0.is_empty()
```
Comment (waynexia) [inline sql/src/ast.rs:34]:
```suggestion
        self.0.0.is_empty()
```

File: sql/src/ast.rs [hunk 2]
```diff
@@ -26,6 +26,32 @@ pub enum Statement {
...
+}
+
+impl ToString for TableName {
+    fn to_string(&self) -> String {
+        self.0
+             .0
+            .iter()
+            .map(|ident| ident.value.as_str())
+            .collect::<Vec<_>>()
+            .join(".")
```
Comment (waynexia) [inline sql/src/ast.rs:45]:
```suggestion
    fn to_string(&self) -> String {
        self.0
            .0
            .iter()
            .map(|ident| ident.value.as_str())
            .collect::<Vec<_>>()
            .join(".")
```

**Review by waynexia — APPROVED** [review]
Good job :+1: But looks like the codes are not formatted, could you please check them?

**Comment by waynexia** [comment]
Also wondering why ci can pass 🧐

File: sql/src/ast.rs (hunk 2 above)
Comment (jiacai2050) [reply sql/src/ast.rs:45]: same with before.

File: sql/src/ast.rs (hunk 1 above)
Comment (waynexia) [reply sql/src/ast.rs:34]: okay, TIL

File: sql/src/ast.rs (hunk 2 above)
Comment (waynexia) [reply sql/src/ast.rs:45]: I can understand the first one but this is pretty strange to me. anyway it goes out of the scope of this PR.
