### PR TITLE
fix: insert negative number value

### LINKED ISSUE #211: Fail to insert negative value
### Describe this problem

Now, CeresDB reports error when inserting a negative value (int or double).

### Steps to reproduce

Execute following sqls:
```sql
CREATE TABLE `test_negative_insert` (`t` timestamp not null, `v` int, TIMESTAMP KEY(t))

INSERT INTO test_negative_insert (t,  v) VALUES (1660233600000, -1);
```

Error message will be thrown:
```plaintext
err:Failed to create plan, query:INSERT INTO test_negative_insert (t,  v) VALUES (1660233600000, -1);, err:Failed to create plan, err:Invalid insert stmt, source expr is not value
```

### Expected behavior

Succeed in inserting negative values.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ShiKaiWi**
# Which issue does this PR close?

Closes #211

# Rationale for this change
 Now CeresDB reports failure when inserting negative number value and that is a bug needing fix. And the bug actually will lead to the failure of inserting any **explicitly signed** number.

# What changes are included in this PR?
Fix the parsing procedure from `Expr` to `Datum` to ensure numbers with sign are allowed to insert.

# Are there any user-facing changes?
None.

# How does this change test
Add new UT tests and integration tests.

### CODE REVIEW

**Review by waynexia — APPROVED** [review]
The code is pretty and tests are concrete, LGTM 👍 

BTW, CI failed...

File: common_types/src/datum.rs [hunk 1]
```diff
@@ -485,6 +485,31 @@ impl Datum {
         }
     }
 
+    /// Generate a negative datum if possible.
+    ///
+    /// It will return `None` if:
+    /// - The data type has no negative value;
+    /// - The negative value overflows;
```
Comment (chunshao90) [inline common_types/src/datum.rs:492]: Replace `;` wth `.`.

Comment (waynexia) [inline common_types/src/datum.rs:492]:
```suggestion
    /// - The data type has no negative value.
    /// - The negative value overflows.
```
