### PR TITLE
fix:Disallow defining timestamp key column as Tag column

### LINKED ISSUE #354: Disallow defining timestamp key column  as Tag column
### Describe this problem

Now we can define the timestamp key column as tag column, but that is totally meaningless and leads to bad performance.

### Steps to reproduce

Execute the sql to create a table:
```sql
CREATE TABLE IF NOT EXISTS demo (
    name string TAG,
    value double,
    t timestamp NOT NULL TAG,
    TIMESTAMP KEY(t)) ENGINE=Analytic with (enable_ttl=false);
```

### Expected behavior

It should fail rather than succeed.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by QuintinTao**
# Which issue does this PR close?

Closes #354

# Rationale for this change
 Fix defining timestamp key column as Tag column bug, refer to https://github.com/CeresDB/ceresdb/issues/354 .

# What changes are included in this PR?

sql/planner.rs -> create_table_to_plan function 

# Are there any user-facing changes?

# How does this change test
curl --location --request POST 'http://127.0.0.1:5440/sql' --header 'Content-Type: application/json' --data-binary '{
    "query": "CREATE TABLE IF NOT EXISTS `demo1` (`name` string TAG,`value` double, t timestamp NOT NULL TAG,TIMESTAMP KEY(t)) ENGINE=Analytic with (enable_ttl='\''false'\'')"
}'

### CODE REVIEW

File: sql/src/planner.rs [hunk 1]
```diff
@@ -380,6 +383,15 @@ impl<'a, P: MetaProvider> PlannerDelegate<'a, P> {
...
         let timestamp_name = timestamp_name.context(RequireTimestamp)?;
+        // The timestamp key column must not be a Tag column
+        if name_column_map.get(&timestamp_name as &str).is_some() {
+            ensure!(
+                !name_column_map.get(&timestamp_name as &str).unwrap().is_tag,
+                TimestampColumnCanNotTag {
+                    name: &timestamp_name as &str,
+                }
+            )
+        }
```
Comment (ShiKaiWi) [inline sql/src/planner.rs:394]: Maybe we can put it like:
```suggestion
        if let Some(timestamp_column) = name_column_map.get(&timestamp_name) {
            ensure!(
                !timestamp_column.is_tag,
                TimestampColumnCanNotTag {
                    name: &timestamp_name,
                }
            )
        }
```

File: sql/src/planner.rs [hunk 2]
```diff
@@ -106,6 +106,9 @@ pub enum Error {
     #[snafu(display("Tag column not found, name:{}", name))]
     TagColumnNotFound { name: String },
 
+    #[snafu(display("Timestamp column can not be Tag, name:{}", name))]
+    TimestampColumnCanNotTag { name: String },
```
Comment (ShiKaiWi) [inline sql/src/planner.rs:110]: A better name may be `TimestampKeyTag` (Timestamp column is different from timestamp key):
```suggestion
    #[snafu(display("Timestamp key column can not be tag, name:{}.\nBactrace:\n{:?}", name, backtrace))]
    TimestampKeyTag { name: String, backtrace: Backtrace },
```

File: sql/src/planner.rs (hunk 1 above)
Comment (QuintinTao) [reply sql/src/planner.rs:394]: OK I will. Thanks

File: sql/src/planner.rs (hunk 2 above)
Comment (QuintinTao) [reply sql/src/planner.rs:110]: OK

File: sql/src/planner.rs [hunk 3]
```diff
@@ -380,6 +387,15 @@ impl<'a, P: MetaProvider> PlannerDelegate<'a, P> {
...
         let timestamp_name = timestamp_name.context(RequireTimestamp)?;
+        // The timestamp key column must not be a Tag column
+        if let Some(timestamp_column) = name_column_map.get(&timestamp_name as &str) {
+            ensure!(
+                !timestamp_column.is_tag,
+                TimestampKeyTag {
+                    name: &timestamp_name as &str,
+                }
+            )
+        }
```
Comment (ShiKaiWi) [inline sql/src/planner.rs:398]: I guess `as &str` is no need:
```suggestion
        if let Some(timestamp_column) = name_column_map.get(&timestamp_name) {
            ensure!(
                !timestamp_column.is_tag,
                TimestampKeyTag {
                    name: &timestamp_name,
                }
            )
        }
```

Comment (QuintinTao) [reply sql/src/planner.rs:398]: if I remove here
 if let Some(timestamp_column) = name_column_map.get(&timestamp_name as &str)

error[E0277]: the trait bound `&str: Borrow<std::string::String>` is not satisfied
   --> sql/src/planner.rs:391:57
    |
391 |         if let Some(timestamp_column) = name_column_map.get(&timestamp_name) {
    |                                                         ^^^ the trait `Borrow<std::string::String>` is not implemented for `&str`
    |
    = help: the trait `Borrow<str>` is implemented for `std::string::String`
note: required by a bound in `BTreeMap::<K, V, A>::get`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sql` due to previous error

But we can remove here

 TimestampKeyTag {
                    name: &timestamp_name,
                }

Comment (ShiKaiWi) [reply sql/src/planner.rs:398]: I see. I guess we can put it as:
```rust
        if let Some(timestamp_column) = name_column_map.get(&timestamp_name.as_str()) {
            ensure!(
                !timestamp_column.is_tag,
                TimestampKeyTag {
                    name: &timestamp_name,
                }
            )
        }
```

File: sql/src/planner.rs [hunk 4]
```diff
@@ -380,6 +387,15 @@ impl<'a, P: MetaProvider> PlannerDelegate<'a, P> {
 
         // Timestamp column must be provided.
         let timestamp_name = timestamp_name.context(RequireTimestamp)?;
+        // The timestamp key column must not be a Tag column
+        if let Some(timestamp_column) = name_column_map.get(&timestamp_name as &str) {
```
Comment (ShiKaiWi) [inline sql/src/planner.rs:391]: I find the key type of name_column_map is `&str`, and it will be better if we can put it as:
```suggestion
        if let Some(timestamp_column) = name_column_map.get(&timestamp_name.as_str()) {
```

Comment (QuintinTao) [reply sql/src/planner.rs:391]: OK

**Review by ShiKaiWi — APPROVED** [review]
LGTM! Thanks @QuintinTao
