### PR TITLE
fix: avoid file purge when they are used in queries

### LINKED ISSUE #427: test_table_compact_current panic sometimes in CI
### Describe this problem

After switch sst reader to async, `test_table_compact_current_segment_rocks` testcase will panic
```
---- tests::compaction_test::test_table_compact_current_segment_rocks stdout ----
thread 'tests::compaction_test::test_table_compact_current_segment_rocks' panicked at 'called `Result::unwrap()` on an `Err` value: ErrWithSource { msg: "read record batch", source: ReadFromSubIter { source: PullRecordBatch { source: DecodeRecordBatch { source: ParquetError { source: General("ObjectStoreReader::get_bytes error: Object at location /tmp/.tmpjcYM19/store/100/2199023255554/18.sst not found: No such file or directory (os error 2)"), backtrace: Backtrace(   0: <snafu::backtrace_shim::Backtrace as snafu::GenerateBacktrace>::generate
```

### Steps to reproduce

```
cargo test --workspace test_table_compact_current_segment_rocks
```

### Expected behavior

No panic

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #427 #534

# Rationale for this change
 

# What changes are included in this PR?

- Hold sst reference in merge/chain iterator, so sst cannot be pushed to purge queue when there are queries.

# Are there any user-facing changes?

No

# How does this change test

CI

### CODE REVIEW

File: analytic_engine/src/row_iter/merge.rs [hunk 1]
```diff
@@ -619,6 +620,8 @@ pub struct MergeIterator {
     schema: RecordSchemaWithKey,
     record_batch_builder: RecordBatchWithKeyBuilder,
     origin_streams: Vec<SequencedRecordBatchStream>,
+    /// ssts are kept here to avoid them from being purged.
+    _ssts: Vec<Vec<FileHandle>>,
```
Comment (ShiKaiWi) [inline analytic_engine/src/row_iter/merge.rs:624]: Maybe we can remove the `_` prefix by adding `#[allow(dead_code)]`.

Comment (jiacai2050) [reply analytic_engine/src/row_iter/merge.rs:624]: The directive will be added for whole struct, not this field, which is a bad practice, as others don't know why dead_code is required for this struct.

Comment (ShiKaiWi) [reply analytic_engine/src/row_iter/merge.rs:624]: I guess the directive can be applied only to a specific field.

Comment (jiacai2050) [reply analytic_engine/src/row_iter/merge.rs:624]: Ooops, I will fix this.

**Review by ShiKaiWi — APPROVED** [review]
LGTM
