### PR TITLE
fix: Query fields are sorted by creation

### LINKED ISSUE #60: Query fields are sorted by creation
**Description**
ceresDB doesn't seem to require strict ordering of query result fields.

**Proposal**

Use the order in which fields are created.

**Additional context**

when I create table use: 
```
CREATE TABLE `hello_mysql` (`name` string TAG, `value` double NOT NULL, `t` timestamp NOT NULL, TIMESTAMP KEY(t)) ENGINE=Analytic with (enable_ttl='false');
```
and select it. his field order seems to be random? I found that the query result is wrapped in HashMap.
image

This doesn't seem to have any effect on normal usage, so I don't know if this situation needs improvement.

### PR DESCRIPTION
**Pull request by dust1**
# Which issue does this PR close?

Closes #60 

# Rationale for this change
 

# What changes are included in this PR?

This PR modifies the Response data structure in ceresdb/server/src/handlers/sql.rs. 
* ResponseRow: one record with response
* ResponseRows: type of Vec<ResponseRow>
* ResponseColumn: column struct, for keep column type and name
* Row: Helper type that is convenient for http serialize, this is one map
* mod http_format: ResponseRow in custom format by Serializer
* mod row_format: Row in custom format by Serializer

# Are there any user-facing changes?

not

# How does this change test

### CODE REVIEW

File: server/src/handlers/sql.rs [hunk 1]
```diff
@@ -21,23 +22,39 @@ use crate::handlers::{
...
-    }
-}
-
 // TODO(yingwen): Improve serialize performance
 #[derive(Serialize)]
 #[serde(rename_all = "snake_case")]
 pub enum Response {
     AffectedRows(usize),
-    Rows(Vec<HashMap<String, Datum>>),
+    #[serde(with = "http_format")]
```
Comment (waynexia) [inline server/src/handlers/sql.rs:37]: We can `impl Serialize for ResponseRow` and let `#[derive(Serialize)]` cover this. Then the sub-mod `http_format` and `row_format` can be removed. So do the util struct `Row`.

File: server/src/handlers/sql.rs [hunk 2]
```diff
@@ -128,26 +145,100 @@ fn convert_output(output: Output) -> ArrowResult<Response> {
...
+            let column_names = &record.column_names;
+            // let mut map = seq.serialize_map(Some(column_names.len()))?;
+
+            for rows in &record.data {
+                let data = rows
+                    .iter()
+                    .enumerate()
+                    .map(|(col_idx, datum)| {
+                        let column_name = &column_names[col_idx].name.clone();
+                        (column_name.clone(), datum.clone())
```
Comment (waynexia) [inline server/src/handlers/sql.rs:215]: Those clones might be avoidable. Maybe with some lifetime annotations on `Row` 🧐

**Review by waynexia — COMMENTED** [review]
Thanks @dust1 for fixing this! The implementation generally looks good to me. I left some style comments.

And I'm wondering if we can add some assertions on the serialized JSON format in test (if `SerializeMap` can preserve the ordering, not sure).

**Review by waynexia — APPROVED** [review]
👍 This looks good to me. Thanks @dust1. I'm going to merge it this afternoon.
