### PR TITLE
fix: failure to open a single table does not interrupt the shard's opening process

### LINKED ISSUE #721: Open shard failed because of OB_BUF_NOT_ENOUGH
### Describe this problem

env：
* Wal is based on OBKV
* replay_batch_size is 100

error msg is :
```
2023-03-09 21:30:10.684 INFO [server/src/grpc/meta_event_service/mod.rs:142] Finish handling request from meta, resp:OpenShardResponse { header: Some(ResponseHeader { code: 500, error: "fail to open table, open_request:OpenTableRequest { catalog_name: \"ceresdb\", schema_name: \"public\", schema_id: SchemaId(0), table_name: \"MMM_2196651627_INFLUENCE_DEFAULT\", table_id: TableId(31801), engine: \"Analytic\", shard_id: 54, cluster_version: 1 }. Caused by: Failed to open table, source:Unexpected error, err:Failed to operate table through write worker, space_id:0, table:MMM_2196651627_INFLUENCE_DEFAULT, table_id:31801, err:Channel error, err:Failed to read wal, err:Failed to read log entries, err:Failed to open region, namespace:wal, region_id:54, table_id:31801, err:Failed to scan table, err:Failed to iter result set, table:wal_wal_20230309000000_000054, err:Common error, code:ObException(OB_BUF_NOT_ENOUGH), err:rcode:OB_BUF_NOT_ENOUGH, message:, addr:33.143.20.185:2882, trace_id:Y7BC76F78-0000000000000AA2, server_trace_id:Y7BC76F78-0000000000000AA2." }) }
```

### Steps to reproduce

None

### Expected behavior

Open shard successfully.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MachaelLee**
## Which issue does this PR close?

Closes #721 

## Rationale for this change
 
 The shard will stop opening if opening a table fails, and no other normal tables will be opened in that shard.
 Access to these tables will fail.

## What changes are included in this PR?

* Print warn log if opening a table fails
* Continue to open shard

### CODE REVIEW

File: server/src/grpc/meta_event_service/mod.rs [hunk 1]
```diff
@@ -249,18 +249,16 @@ async fn handle_open_shard(ctx: HandlerContext, request: OpenShardRequest) -> Re
...
+        let result = schema.open_table(open_request.clone(), opts.clone()).await;
+
+        if result.is_ok() {
+            continue;
+        }
+
+        match result.err() {
+            Some(e) => warn!("Failed to open table, open_request:{open_request:?}, error:{e:?}"),
+            None => warn!("No table is opened, open_request:{open_request:?}"),
+        }
```
Comment (Rachelint) [inline server/src/grpc/meta_event_service/mod.rs:261]: match result {


```suggestion
        match result {
            Ok(Some(_)) => {},
            Ok(None) => error!("No table is opened, open_request:{open_request:?}"),
            Err(e) => error!("Failed to open table, open_request:{open_request:?}, error:{e:?}"),
        }
```

File: server/src/grpc/meta_event_service/mod.rs [hunk 2]
```diff
@@ -249,21 +253,44 @@ async fn handle_open_shard(ctx: HandlerContext, request: OpenShardRequest) -> Re
...
+    );
+
+    if err_list.is_empty() {
+        Ok(())
+    } else {
+        Err(Error::OpenShardErr {
+            code: StatusCode::Internal,
+            msg: format!(
+                "Failed to open shard:{},  because of failed tables:{err_list:?}",
+                shard_info.id
```
Comment (chunshao90) [inline server/src/grpc/meta_event_service/mod.rs:290]:
```suggestion
                "Failed to open shard:{shard_info.id}, because of failed tables:{err_list:?}",
```

File: server/src/grpc/meta_event_service/mod.rs [hunk 3]
```diff
@@ -249,21 +253,44 @@ async fn handle_open_shard(ctx: HandlerContext, request: OpenShardRequest) -> Re
...
-                code: StatusCode::Internal,
-                msg: format!("no table is opened, open_request:{open_request:?}"),
-            })?;
+        let result = schema.open_table(open_request.clone(), opts.clone()).await;
+
+        match result {
+            Ok(Some(_)) => {
+                success += 1;
+            }
+            Ok(None) => {
```
Comment (chunshao90) [inline server/src/grpc/meta_event_service/mod.rs:262]: None means table not exists.

File: server/src/grpc/meta_event_service/mod.rs [hunk 4]
```diff
@@ -249,21 +253,44 @@ async fn handle_open_shard(ctx: HandlerContext, request: OpenShardRequest) -> Re
...
+                fail += 1;
+                error!("no table is opened, open_request:{open_request:?}");
+                err_list.push(table.name);
+            }
+            Err(e) => {
```
Comment (chunshao90) [inline server/src/grpc/meta_event_service/mod.rs:267]: Should we reopen the table that failed to open?

File: server/src/grpc/meta_event_service/error.rs [hunk 5]
```diff
@@ -22,13 +22,17 @@ pub enum Error {
         msg: String,
         source: GenericError,
     },
+
+    #[snafu(display("Open shard error, code:{:?}, message:{}", code, msg))]
+    OpenShardErr { code: StatusCode, msg: String },
```
Comment (chunshao90) [inline server/src/grpc/meta_event_service/error.rs:27]: Reuse ErrWithCause instead of defining a new error?

File: server/src/grpc/meta_event_service/mod.rs (hunk 3 above)
Comment (MachaelLee) [reply server/src/grpc/meta_event_service/mod.rs:262]: Actually it occurred. But is is difficult to reproduce.

File: server/src/grpc/meta_event_service/mod.rs (hunk 2 above)
Comment (MachaelLee) [reply server/src/grpc/meta_event_service/mod.rs:290]: This will result in error msg: `invalid format string: field access isn't supported`.

File: server/src/grpc/meta_event_service/mod.rs (hunk 4 above)
Comment (MachaelLee) [reply server/src/grpc/meta_event_service/mod.rs:267]: With my known errors, there is no point to reopen.

File: server/src/grpc/meta_event_service/error.rs (hunk 5 above)
Comment (MachaelLee) [reply server/src/grpc/meta_event_service/error.rs:27]: Sometimes there are many error When opening shard, I cant find a correct source error for ErrWithCause.

Comment (chunshao90) [reply server/src/grpc/meta_event_service/error.rs:27]: How about ErrNoCause?

Comment (MachaelLee) [reply server/src/grpc/meta_event_service/error.rs:27]: ok

File: server/src/grpc/meta_event_service/mod.rs [hunk 6]
```diff
@@ -249,21 +253,42 @@ async fn handle_open_shard(ctx: HandlerContext, request: OpenShardRequest) -> Re
...
+        err_map.len(),
+    );
+
+    if err_map.is_empty() {
+        Ok(())
+    } else {
+        Err(Error::ErrNoCause {
+            code: StatusCode::Internal,
+            msg: format!(
+                "Failed to open shard:{}, because of failed tables:{err_map:?}",
```
Comment (chunshao90) [inline server/src/grpc/meta_event_service/mod.rs:287]: Remove `err_map`. 
If the table fails to open, you only need to print the log and do not need to return.

**Review by chunshao90 — APPROVED** [review]
LGTM
