### PR TITLE
fix: start http server after table recovery finished

### LINKED ISSUE #559: Panicked when create table
### Describe this problem

Here is the stack
```
2023-01-11 11:01:11.797 ERRO [server/src/http.rs:129] Http service Failed to handle sql, err:Failed to create plan, query:DESCRIBE MMM_2197135594_INFLUENCE_GRAY_SANDBOX_OUTPUT_TABLE, err:Failed to create plan, err:Table not found, table:MMM_2197135594_INFLUENCE_GRAY_SANDBOX_OUTPU
T_TABLE
2023-01-11 11:01:11.798 ERRO [common_util/src/panic.rs:42] thread 'ceres-write' panicked 'assertion failed: success' at "analytic_engine/src/space.rs:147"
   0: common_util::panic::set_panic_hook::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/common_util/src/panic.rs:41:18
   1: std::panicking::rust_panic_with_hook
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:142:14
   6: core::panicking::panic
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panicking.rs:48:5
   7: analytic_engine::space::Space::insert_table
             at /home/chunshao.rcs/github/CeresDB/ceresdb/analytic_engine/src/space.rs:147:9
   8: analytic_engine::instance::create::<impl analytic_engine::instance::Instance>::process_create_table_command::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/analytic_engine/src/instance/create.rs:115:9
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
      analytic_engine::instance::write_worker::WriteWorker::handle_create_table::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/analytic_engine/src/instance/write_worker.rs:865:78
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
      analytic_engine::instance::write_worker::WriteWorker::run::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/analytic_engine/src/instance/write_worker.rs:753:50
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
      analytic_engine::instance::write_worker::WriteGroup::new::{{closure}}
             at /home/chunshao.rcs/github/CeresDB/ceresdb/analytic_engine/src/instance/write_worker.rs:616:29
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/future/mod.rs:91:19
  10: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
      tokio::runtime::task::core::CoreStage<T>::poll
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
      tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panicking.rs:456:19
  11: std::panic::catch_unwind
             at /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/std/src/panic.rs:137:14
      tokio::runtime::task::harness::poll_future
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
      tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/chunshao.rcs/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
      tokio::runtime::task::harness::Harness<T,S>::poll
```

### Steps to reproduce

I guess the table had been created and dropped for many times, then panicked when creating the table

### Expected behavior

Create table successfully

### Additional Information

None

### PR DESCRIPTION
**Pull request by jiacai2050**
## Which issue does this PR close?

Closes #559

## Rationale for this change
 
If server start to serve request before table recovery finished, it may happen
panic in issue #559.

## What changes are included in this PR?

- Update HTTP server start location, only start server after table recovery finished, same with gRPC/MySQL server.

## Are there any user-facing changes?

No

## How does this change test

CI and manually.

### CODE REVIEW

File: server/src/server.rs [hunk 1]
```diff
@@ -133,6 +136,12 @@ impl<Q: QueryExecutor + 'static> Server<Q> {
         self.create_default_schema_if_not_exists().await;
 
         info!("Server start, start services");
+        self.http_service
+            .start()
+            .await
+            .with_context(|| HttpService {
+                msg: "start failed".to_string(),
+            })?;
```
Comment (chunshao90) [inline server/src/server.rs:144]:
```suggestion
            .context(HttpService {
                msg: "start failed",
            })?;
```

File: server/src/server.rs [hunk 2]
```diff
@@ -333,7 +341,9 @@ impl<Q: QueryExecutor + 'static> Builder<Q> {
             .schema_config_provider(provider.clone())
             .config_content(config_content)
             .build()
-            .context(StartHttpService)?;
+            .with_context(|| HttpService {
+                msg: "build failed".to_string(),
+            })?;
```
Comment (chunshao90) [inline server/src/server.rs:346]:
```suggestion
            .context(HttpService {
                msg: "build failed",
            })?;
```

**Review by chunshao90 — APPROVED** [review]
LGTM
